# Generated by Django 5.2.5 on 2025-08-08 16:06

import cloudinary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Merchandising', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PointDeVente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(editable=False, max_length=20, unique=True)),
                ('no_pdv', models.CharField(max_length=50, unique=True)),
                ('region', models.CharField(max_length=100)),
                ('wilaya', models.CharField(max_length=100)),
                ('commune', models.CharField(max_length=100)),
                ('type_pdv', models.CharField(choices=[('epicerie', 'Épicerie'), ('supermarche', 'Supermarché'), ('hypermarché', 'Hypermarché'), ('autre', 'Autre')], max_length=50)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
            ],
        ),
        migrations.CreateModel(
            name='Concurrent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='concurrents', to='Merchandising.client')),
            ],
        ),
        migrations.CreateModel(
            name='ProduitClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('categorie', models.CharField(max_length=100)),
                ('format', models.CharField(max_length=100)),
                ('image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produits', to='Merchandising.client')),
            ],
        ),
        migrations.CreateModel(
            name='ProduitConcurrent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('categorie', models.CharField(max_length=100)),
                ('format', models.CharField(max_length=100)),
                ('image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image')),
                ('concurrent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produits', to='Merchandising.concurrent')),
            ],
        ),
    ]
