# Generated by Django 5.2.5 on 2025-08-08 17:31

import cloudinary.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Merchandising', '0002_pointdevente_concurrent_produitclient_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(editable=False, max_length=20, unique=True)),
                ('date_mission', models.DateField()),
                ('etat', models.CharField(choices=[('planned', 'Planifiée'), ('in_progress', 'En cours'), ('done', 'Faite'), ('failed', 'Échouée')], default='planned', max_length=20)),
                ('raison_echec', models.CharField(blank=True, choices=[('pdv_closed', 'PDV fermé'), ('other', 'Autre raison')], max_length=50, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='missions_created', to=settings.AUTH_USER_MODEL)),
                ('merchandiser', models.ForeignKey(limit_choices_to={'role': 'merchandiser'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('pdv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='missions', to='Merchandising.pointdevente')),
            ],
        ),
        migrations.CreateModel(
            name='PhotoMission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categorie', models.CharField(max_length=100)),
                ('image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('type_photo', models.CharField(choices=[('avant', 'Avant'), ('après', 'Après')], max_length=5)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('mission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='Merchandising.mission')),
            ],
        ),
        migrations.CreateModel(
            name='RealisationClientData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_realisation', models.DateField(auto_now_add=True)),
                ('disponible', models.BooleanField(default=False, help_text='Produit disponible dans le PDV')),
                ('handling', models.BooleanField(default=False, help_text='Le produit est-il bien présenté ?')),
                ('facing_share', models.FloatField(blank=True, help_text='Part de linéaire (%)', null=True)),
                ('prix_vente', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('stock', models.PositiveIntegerField(blank=True, null=True)),
                ('merch', models.ForeignKey(limit_choices_to={'role': 'merchandiser'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('mission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Merchandising.mission')),
                ('pdv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Merchandising.pointdevente')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Merchandising.produitclient')),
            ],
        ),
        migrations.CreateModel(
            name='RealisationConcurrenceData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_realisation', models.DateField(auto_now_add=True)),
                ('disponible', models.BooleanField(default=False)),
                ('facing_share', models.FloatField(blank=True, null=True)),
                ('prix_vente', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('stock', models.PositiveIntegerField(blank=True, null=True)),
                ('merch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='realisation_concurrent_merch', to=settings.AUTH_USER_MODEL)),
                ('mission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Merchandising.mission')),
                ('pdv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Merchandising.pointdevente')),
                ('produit_concurrent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Merchandising.produitconcurrent')),
            ],
        ),
    ]
