# Generated by Django 5.2.5 on 2025-08-09 10:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Merchandising', '0004_mission_begin_latitude_mission_begin_longitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projet',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clien_staff', to='Merchandising.client'),
        ),
    ]
