# Generated by Django 5.2.5 on 2025-08-09 10:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Merchandising', '0006_customuser_client_alter_projet_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mission',
            name='merchandiser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Merchandising.client'),
        ),
    ]
