# Generated by Django 5.2.5 on 2025-08-09 10:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Merchandising', '0007_alter_mission_merchandiser'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clien_missions', to='Merchandising.client'),
        ),
        migrations.AddField(
            model_name='photomission',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clien_photos', to='Merchandising.client'),
        ),
        migrations.AddField(
            model_name='realisationclientdata',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clien_realisations', to='Merchandising.client'),
        ),
        migrations.AddField(
            model_name='realisationconcurrencedata',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clien_realisation_concurrent', to='Merchandising.client'),
        ),
        migrations.AlterField(
            model_name='mission',
            name='merchandiser',
            field=models.ForeignKey(limit_choices_to={'role': 'merchandiser'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
