# Generated by Django 5.2.5 on 2025-08-09 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Merchandising', '0008_mission_client_photomission_client_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='realisationclientdata',
            name='region',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='realisationclientdata',
            name='wilaya',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='realisationconcurrencedata',
            name='region',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='realisationconcurrencedata',
            name='wilaya',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
