# Generated by Django 5.2.5 on 2025-08-09 11:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Merchandising', '0009_realisationclientdata_region_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='photomission',
            name='pdv',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photos_pdv', to='Merchandising.pointdevente'),
        ),
        migrations.AddField(
            model_name='photomission',
            name='region',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='photomission',
            name='wilaya',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
